projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: "${env:SERVER_ENDPOINT}"
  database:
    schemaPath: "src/generated/database.graphql" # Where to put generated schema
    extensions:
      prisma: database/prisma.yml # Prisma config file path
      binding:
        output: src/generated/prisma.ts # Where to put generated files
        generator: prisma-ts # Which binding generator should be used