projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: "${env:SERVER_ENDPOINT}"
  database:
    schemaPath: "src/generated/database.graphql"
    extensions:
      graphcool: graphcool.yml
      binding:
        output: src/generated/graphcool.ts
        generator: graphcool-ts